// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DataFrame")>]
[<assembly: AssemblyProductAttribute("DataFrame")>]
[<assembly: AssemblyDescriptionAttribute("data frame library for .NET based on ML.NET IDataView")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DataFrame"
    let [<Literal>] AssemblyProduct = "DataFrame"
    let [<Literal>] AssemblyDescription = "data frame library for .NET based on ML.NET IDataView"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
